import React from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
// import PlayerList from './PlayerList'
import PlayerCard from './PlayerCard'